"""add manager_id to projects

Revision ID: 4d6782b4f019
Revises: d2adf26bb8c4
Create Date: 2026-07-19 02:12:14.621584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d6782b4f019'
down_revision: Union[str, Sequence[str], None] = 'd2adf26bb8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_manager_id'), 'projects', ['manager_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['manager_id'], ['id'])
    
    # Populate existing records with the user_id of the project manager
    op.execute("""
        UPDATE projects p
        SET manager_id = COALESCE(
            (
                SELECT pm.user_id
                FROM project_members pm
                JOIN users u ON pm.user_id = u.id
                JOIN roles r ON u.role_id = r.id
                WHERE pm.project_id = p.id
                  AND r.name = 'Project Manager / Product Owner / Group Member'
                ORDER BY pm.id ASC
                LIMIT 1
            ),
            (
                SELECT pm.user_id
                FROM project_members pm
                JOIN users u ON pm.user_id = u.id
                JOIN roles r ON u.role_id = r.id
                WHERE pm.project_id = p.id
                  AND r.name = 'Leader'
                ORDER BY pm.id ASC
                LIMIT 1
            ),
            (
                SELECT pm.user_id
                FROM project_members pm
                WHERE pm.project_id = p.id
                ORDER BY pm.id ASC
                LIMIT 1
            )
        )
        WHERE manager_id IS NULL OR manager_id = created_by
    """)
    
    op.alter_column('users', 'avatar_url',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_manager_id'), table_name='projects')
    op.drop_column('projects', 'manager_id')
    # ### end Alembic commands ###
