"""add is_active to project_members

Revision ID: 946e2d6799af
Revises: b47dbc775d94
Create Date: 2026-07-10 15:59:40.001934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '946e2d6799af'
down_revision: Union[str, Sequence[str], None] = 'b47dbc775d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'project_members',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.execute(
        """
        UPDATE project_members
        SET is_active = TRUE
        WHERE is_active IS NULL
        """
    )
    op.alter_column('project_members', 'is_active', existing_type=sa.Boolean(), server_default=None)
    op.create_index(op.f('ix_project_members_is_active'), 'project_members', ['is_active'], unique=False)
    op.alter_column('users', 'avatar_url',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_project_members_is_active'), table_name='project_members')
    op.drop_column('project_members', 'is_active')
    # ### end Alembic commands ###
